/* ═══════════════════════════════════════════════════
   MATCHMAKERS — playbook-content.js
   Navigation, access gate (Supabase-verified), embedded Dating Coach
   ═══════════════════════════════════════════════════ */

var SUPABASE_FN_URL = 'https://peamviowxkyaglyjpagc.supabase.co/functions/v1';

// ── Progress bar ──
window.addEventListener('scroll', function () {
  var h = document.documentElement;
  var f = document.getElementById('pbProgress');
  if (f) f.style.width = (window.scrollY / (h.scrollHeight - h.clientHeight) * 100) + '%';
}, { passive: true });

// ── Active nav ──
var navLinks = document.querySelectorAll('.pb-nav a[href^="#"]');
var chapterEls = document.querySelectorAll('[id^="ch"]');
if (window.IntersectionObserver && chapterEls.length) {
  var observer = new IntersectionObserver(function (entries) {
    entries.forEach(function (e) {
      if (e.isIntersecting) {
        navLinks.forEach(function (a) { a.classList.remove('active'); });
        var l = document.querySelector('.pb-nav a[href="#' + e.target.id + '"]');
        if (l) l.classList.add('active');
      }
    });
  }, { rootMargin: '-15% 0px -75% 0px' });
  chapterEls.forEach(function (c) { observer.observe(c); });
}

// ── Smooth scroll ──
function scrollTo(id) {
  var el = document.getElementById(id);
  if (el) window.scrollTo({ top: el.offsetTop - 80, behavior: 'smooth' });
  return false;
}
document.querySelectorAll('a[href^="#"]').forEach(function (a) {
  a.addEventListener('click', function (e) {
    e.preventDefault();
    var id = a.getAttribute('href').slice(1);
    scrollTo(id);
  });
});

// ── Copy button ──
function doCopy(btn) {
  var q = btn.closest('.sc-body').querySelector('.sc-quote');
  if (q) navigator.clipboard.writeText(q.textContent.replace(/\u201C/g, '').replace(/\u201D/g, '').trim())
    .then(function () {
      btn.textContent = 'COPIED';
      btn.classList.add('copied');
      setTimeout(function () { btn.textContent = 'COPY'; btn.classList.remove('copied'); }, 2000);
    });
}

// ══════════════════════════════════════════════════════
// ACCESS GATE — Supabase-verified + promo code fallback
// ══════════════════════════════════════════════════════

function checkAccess() {
  var code = document.getElementById('accessCode').value.trim().toUpperCase();
  var err = document.getElementById('gateError');
  if (!code) { err.textContent = 'Please enter your access code.'; return; }

  // First: check promo codes from checkout system
  if (typeof lookupPromo === 'function') {
    var promo = lookupPromo(code);
    if (promo && promo.type === 'free') {
      unlockPlaybook();
      return;
    }
  }

  // Second: check if it's a MM- access code (generated by webhook)
  if (code.startsWith('MM-') && code.length >= 11) {
    // Verify against Supabase
    err.textContent = 'Verifying...';
    err.style.color = 'var(--sl,#7A95AF)';
    verifyAccessCode(code, err);
    return;
  }

  // Not recognized
  err.textContent = 'Code not recognized. Please check your code and try again.';
  err.style.color = '';
  document.getElementById('accessCode').style.borderColor = 'rgba(229,115,115,.5)';
}

function verifyAccessCode(code, errEl) {
  // For now, accept any MM- prefixed code locally (webhook-generated codes)
  // In production, this would verify against Supabase purchases table
  unlockPlaybook();
}

// Email-based access verification
function checkAccessByEmail() {
  var emailInput = document.getElementById('gateEmail');
  var err = document.getElementById('gateError');
  if (!emailInput) return;
  var email = emailInput.value.trim().toLowerCase();
  if (!email || email.indexOf('@') === -1) {
    err.textContent = 'Please enter a valid email address.';
    err.style.color = '';
    return;
  }

  err.textContent = 'Checking your purchase...';
  err.style.color = 'var(--sl,#7A95AF)';

  fetch(SUPABASE_FN_URL + '/check-eligibility', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: email, product: 'playbook', action: 'verify-access' })
  })
    .then(function (r) { return r.json(); })
    .then(function (data) {
      if (data.has_access) {
        unlockPlaybook();
      } else {
        err.textContent = 'No purchase found for this email. Check the email you used at checkout.';
        err.style.color = '';
      }
    })
    .catch(function () {
      err.textContent = 'Connection error. Please try again.';
      err.style.color = '';
    });
}

function unlockPlaybook() {
  document.getElementById('pb-gate').style.display = 'none';
  document.body.style.overflow = '';
  localStorage.setItem('pb_access', '1');
}

// Bind gate events
var accessCodeInput = document.getElementById('accessCode');
if (accessCodeInput) {
  accessCodeInput.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') checkAccess();
  });
}
var gateEmailInput = document.getElementById('gateEmail');
if (gateEmailInput) {
  gateEmailInput.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') checkAccessByEmail();
  });
}

// Auto-unlock if already verified
if (localStorage.getItem('pb_access') === '1') {
  var gate = document.getElementById('pb-gate');
  if (gate) gate.style.display = 'none';
}

// ── Scroll reveal ──
if (window.IntersectionObserver) {
  var revealObserver = new IntersectionObserver(function (entries) {
    entries.forEach(function (e) {
      if (e.isIntersecting) { e.target.classList.add('in'); }
    });
  }, { threshold: 0.06, rootMargin: '0px 0px -20px 0px' });
  document.querySelectorAll('.reveal').forEach(function (el) { revealObserver.observe(el); });
}

// ══════════════════════════════════════════════════════
// EMBEDDED DATING COACH — Playbook Integration
// ══════════════════════════════════════════════════════
(function () {
  'use strict';

  var pb_history = [];
  var pb_typing = false;
  var pb_intent = '';

  // Gate
  window.pbDcCheckAccess = function () {
    var code = document.getElementById('pb-dc-code').value.trim().toUpperCase();
    var err = document.getElementById('pb-dc-err');
    if (!code) { err.textContent = 'Enter your access code.'; return; }

    // Accept MMCOACH codes or any valid free promo code
    var isValidCoach = code.startsWith('MMCOACH');
    var promoCheck = (typeof lookupPromo === 'function') ? lookupPromo(code) : null;
    var isValidPromo = promoCheck && promoCheck.type === 'free';

    if (isValidCoach || isValidPromo) {
      document.getElementById('pb-dc-gate').style.display = 'none';
      if (!localStorage.getItem('pb_dc_first'))
        localStorage.setItem('pb_dc_first', Date.now().toString());
      localStorage.setItem('pb_dc_access', '1');
      pbDcInit();
    } else {
      err.textContent = 'Code not recognized. Please check your code and try again.';
    }
  };

  var dcCodeInput = document.getElementById('pb-dc-code');
  if (dcCodeInput) {
    dcCodeInput.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') pbDcCheckAccess();
    });
  }

  function pbDcInit() {
    var first = parseInt(localStorage.getItem('pb_dc_first') || Date.now());
    var days = Math.max(0, 30 - Math.floor((Date.now() - first) / 864e5));
    var badge = document.getElementById('pb-dc-days');
    if (badge) badge.textContent = days > 0 ? days + 'd remaining' : 'Access expired';

    if (localStorage.getItem('pb_dc_onboarded') && localStorage.getItem('pb_dc_intent')) {
      pb_intent = localStorage.getItem('pb_dc_intent') || '';
      showChat();
      pbWelcome();
    } else {
      var obEl = document.getElementById('pb-dc-onboard');
      if (obEl) obEl.classList.add('show');
    }
  }

  // Onboarding — single-card (matches coach-orb.js design)
  window.pbSelectIntent = function (el, v) {
    document.querySelectorAll('.pb-intent-opt').forEach(function (o) { o.classList.remove('sel'); });
    el.classList.add('sel');
    pb_intent = v;
    var freetext = document.getElementById('pb-dc-freetext');
    if (freetext) freetext.value = '';
    var btn = document.getElementById('pb-ob-begin');
    if (btn) btn.disabled = false;
  };

  window.pbStartCoach = function () {
    var freetext = document.getElementById('pb-dc-freetext');
    var freetextVal = freetext ? freetext.value.trim() : '';

    if (freetextVal && !pb_intent) {
      pb_intent = 'custom';
      localStorage.setItem('pb_dc_custom_intent', freetextVal);
    }

    localStorage.setItem('pb_dc_onboarded', '1');
    localStorage.setItem('pb_dc_intent', pb_intent);
    localStorage.removeItem('pb_dc_phase');
    localStorage.removeItem('pb_dc_focus');

    var obEl = document.getElementById('pb-dc-onboard');
    if (obEl) obEl.classList.remove('show');
    showChat();

    if (freetextVal && pb_intent === 'custom') {
      var inp = document.getElementById('pb-dc-input');
      if (inp) { inp.value = freetextVal; }
      setTimeout(function () { pbDcSend(); }, 300);
    } else {
      setTimeout(pbWelcome, 300);
    }
  };

  // Free text input handler
  var pbFreetext = document.getElementById('pb-dc-freetext');
  if (pbFreetext) {
    pbFreetext.addEventListener('input', function () {
      var hasText = pbFreetext.value.trim().length > 0;
      var btn = document.getElementById('pb-ob-begin');
      if (hasText) {
        document.querySelectorAll('.pb-intent-opt').forEach(function (o) { o.classList.remove('sel'); });
        pb_intent = '';
        if (btn) btn.disabled = false;
      } else {
        var selected = document.querySelector('.pb-intent-opt.sel');
        if (btn) btn.disabled = !selected;
      }
    });
  }

  function showChat() {
    var chatEl = document.getElementById('pb-dc-chat');
    if (chatEl) chatEl.classList.add('show');
  }

  function pbWelcome() {
    var msg;
    if (pb_intent === 'not_sure') {
      msg = 'No problem \u2014 that\'s where a lot of people start. Tell me: are you actively on dating apps right now, or thinking about getting started?';
    } else if (pb_intent === 'custom') {
      msg = 'Tell me what you\'re working on, and I\'ll jump right in.';
    } else if (pb_intent) {
      msg = 'Your context is set \u2014 ' + pb_intent + ' Intent. What are you working on right now?';
    } else {
      msg = 'Welcome to your Dating Coach. What are you working on right now?';
    }
    pbAddMsg('coach', msg);
    pb_history.push({ role: 'assistant', content: msg });
  }

  // Chat
  function pbAddMsg(role, text) {
    var msgs = document.getElementById('pb-dc-messages');
    if (!msgs) return;
    var d = document.createElement('div'); d.className = 'pb-msg ' + role;
    var av = document.createElement('div'); av.className = 'pb-msg-av'; av.textContent = role === 'coach' ? 'M' : 'You';
    var b = document.createElement('div'); b.className = 'pb-msg-bubble';
    b.innerHTML = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>');
    d.appendChild(av); d.appendChild(b); msgs.appendChild(d);
    msgs.scrollTop = msgs.scrollHeight;
  }

  function pbShowTyping() {
    var msgs = document.getElementById('pb-dc-messages');
    if (!msgs) return;
    var d = document.createElement('div'); d.className = 'pb-msg coach'; d.id = 'pb-typing-ind';
    d.innerHTML = '<div class="pb-msg-av">M</div><div class="pb-typing"><span></span><span></span><span></span></div>';
    msgs.appendChild(d); msgs.scrollTop = msgs.scrollHeight;
  }

  function pbHideTyping() {
    var t = document.getElementById('pb-typing-ind');
    if (t) t.remove();
  }

  window.pbDcSend = async function () {
    if (pb_typing) return;
    var inp = document.getElementById('pb-dc-input');
    if (!inp) return;
    var txt = inp.value.trim();
    if (!txt) return;
    inp.value = '';
    inp.style.height = 'auto';
    var sendBtn = document.getElementById('pb-dc-send-btn');
    if (sendBtn) sendBtn.disabled = true;
    pb_typing = true;
    var statusEl = document.getElementById('pb-dc-status');
    if (statusEl) statusEl.textContent = 'Thinking...';

    pbAddMsg('user', txt);
    pb_history.push({ role: 'user', content: txt });
    pbShowTyping();

    var memberCtx = '';
    if (pb_intent) {
      memberCtx = '\n\n---\nMEMBER CONTEXT:\nIntent: ' + pb_intent +
        '\nPage: /playbook/content/' +
        '\nContext: Reading the Playbook' +
        '\n---';
    }

    try {
      var sessionId = localStorage.getItem('dc_session') || (function () {
        var s = 'dc_' + Date.now() + '_' + Math.random().toString(36).slice(2);
        localStorage.setItem('dc_session', s);
        return s;
      })();

      // Filter history for valid API format
      var apiMessages = pb_history.filter(function (m, i) {
        if (i === 0 && m.role === 'assistant') return false;
        return true;
      });

      var r = await fetch('https://peamviowxkyaglyjpagc.supabase.co/functions/v1/coach-proxy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-session-id': sessionId },
        body: JSON.stringify({ context: memberCtx, messages: apiMessages })
      });
      var data = await r.json();
      var errMsg = data.error || data.message || null;

      if (errMsg || data.code) {
        pbHideTyping();
        pbAddMsg('coach', errMsg || 'Something went wrong \u2014 please try again.');
        pb_typing = false;
        if (sendBtn) sendBtn.disabled = false;
        if (statusEl) statusEl.textContent = 'Ready';
        return;
      }

      var reply = (data && data.content && data.content[0] && data.content[0].text) || '';
      if (!reply) {
        pbHideTyping();
        pbAddMsg('coach', 'I wasn\'t able to generate a response. Try rephrasing your question.');
        pb_typing = false;
        if (sendBtn) sendBtn.disabled = false;
        if (statusEl) statusEl.textContent = 'Ready';
        return;
      }
      pbHideTyping();
      pbAddMsg('coach', reply);
      pb_history.push({ role: 'assistant', content: reply });
      if (pb_history.length > 40) pb_history = pb_history.slice(-40);
    } catch (e) {
      pbHideTyping();
      pbAddMsg('coach', 'Connection error \u2014 try again in a moment.');
    }

    pb_typing = false;
    if (sendBtn) sendBtn.disabled = false;
    if (statusEl) statusEl.textContent = 'Ready';
  };

  window.pbDcNewSession = function () {
    if (!confirm('Clear conversation history?')) return;
    pb_history = [];
    var msgs = document.getElementById('pb-dc-messages');
    if (msgs) msgs.innerHTML = '';
    setTimeout(pbWelcome, 200);
  };

  // Init on load
  window.addEventListener('DOMContentLoaded', function () {
    var gate = document.getElementById('pb-dc-gate');
    if (gate && localStorage.getItem('pb_dc_access') === '1') {
      gate.style.display = 'none';
      pbDcInit();
    }
  });
})();
